# Generated by Django 2.2.13 on 2021-02-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0100_financialmodel_om_and_replacement_present_cost_after_tax_us_dollars'),
        ('reo', '0078_merge_20210108_2229'),
    ]

    operations = [
    ]
