# Generated by Django 2.2.13 on 2021-02-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0101_merge_20210222_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boilermodel',
            old_name='year_one_emissions_bau_lb_C02',
            new_name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RenameField(
            model_name='boilermodel',
            old_name='year_one_emissions_lb_C02',
            new_name='year_one_emissions_lb_CO2',
        ),
        migrations.RenameField(
            model_name='chpmodel',
            old_name='year_one_emissions_bau_lb_C02',
            new_name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RenameField(
            model_name='chpmodel',
            old_name='year_one_emissions_lb_C02',
            new_name='year_one_emissions_lb_CO2',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='renewable_generation_accounting_method',
            new_name='renewable_electricity_accounting_method',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='renewable_electricity_energy_pct',
            new_name='renewable_electricity_max_pct',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='renewable_generation_min_pct',
            new_name='renewable_electricity_min_pct',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_generation_bau_kwh',
            new_name='year_one_renewable_electricity_bau_kwh',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_generation_bau_pct',
            new_name='year_one_renewable_electricity_bau_pct',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_generation_kwh',
            new_name='year_one_renewable_electricity_kwh',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_generation_pct',
            new_name='year_one_renewable_electricity_pct',
        ),
        migrations.RemoveField(
            model_name='pvmodel',
            name='year_one_scope1_emissions_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='pvmodel',
            name='year_one_scope1_emissions_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='pvmodel',
            name='year_one_scope1_emissions_series_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='pvmodel',
            name='year_one_scope1_emissions_series_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='renewable_generation_max_pct',
        ),
        migrations.RemoveField(
            model_name='windmodel',
            name='year_one_scope1_emissions_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='windmodel',
            name='year_one_scope1_emissions_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='windmodel',
            name='year_one_scope1_emissions_series_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='windmodel',
            name='year_one_scope1_emissions_series_lb_CO2',
        ),
        migrations.AddField(
            model_name='fueltariffmodel',
            name='boiler_fuel_percent_RE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fueltariffmodel',
            name='boiler_fuel_percent_biogenic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fueltariffmodel',
            name='chp_fuel_percent_RE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fueltariffmodel',
            name='chp_fuel_percent_biogenic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='generator_fuel_percent_RE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='generator_fuel_percent_biogenic',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
