# Generated by Django 2.2.13 on 2021-02-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0102_auto_20210223_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemodel',
            name='renewable_electricity_min_pct',
        ),
    ]
