# Generated by Django 2.2.13 on 2021-02-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0103_remove_sitemodel_renewable_electricity_min_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='renewable_electricity_min_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
