# Generated by Django 3.1.12 on 2021-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0104_auto_20210409_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='annual_income_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='desired_energy_burden_threshold_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_energy_burden_bau_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_energy_burden_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
