# Generated by Django 2.2.13 on 2021-04-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0105_auto_20210406_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_cost_of_emissions_reduction_us_dollars_per_ton_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_heat_bau_mmbtu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_heat_bau_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_heat_mmbtu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_heat_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
