# Generated by Django 2.2.13 on 2021-04-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0106_auto_20210420_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_bau_input_lb_CO2',
            new_name='preprocessed_year_one_emissions_bau_lb_CO2',
        ),
    ]
