# Generated by Django 2.2.13 on 2021-04-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0108_auto_20210422_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemodel',
            name='renewable_electricity_accounting_method',
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='include_exported_renewable_electricity_in_total',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
