# Generated by Django 3.1.12 on 2021-07-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0109_auto_20210422_2136'),
        ('reo', '0104_auto_20210409_1454'),
    ]

    operations = [
    ]
